[phases.setup]
nixPkgs = ["openssl", "pkg-config"]

[phases.build]
cmds = ["cargo build --release", "mkdir -p /out/bin", "cp target/release/evertext_bot_rust /out/bin/", "cp db.json /out/bin/"]

[start]
cmd = "./evertext_bot_rust"
