[phases.setup]
nixPkgs = ["openssl", "pkg-config"]

[phases.build]
cmds = [
    "cargo build --release", 
    "mkdir -p /app", 
    "cp target/release/evertext_bot_rust /app/", 
    "cp db.json /app/"
]

[start]
cmd = "/app/evertext_bot_rust"
